# Generated by Django 6.0.4 on 2026-04-24 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        ('guardrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guardpost',
            name='assigned_personnel',
            field=models.ManyToManyField(blank=True, related_name='guard_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardroom',
            name='ic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardroom_commanded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardroom',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardroom', to='formations.unit'),
        ),
        migrations.AddField(
            model_name='guardpost',
            name='guardroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='guardrooms.guardroom'),
        ),
    ]
