# Generated by Django 6.0.4 on 2026-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardrooms', '0003_guardroom_unit_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardroom',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guardroom',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='guardroom',
            name='phone_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
