# Generated by Django 6.0.4 on 2026-06-03 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_casecourtmartialattachment'),
        ('guardrooms', '0004_guardroom_capacity_guardroom_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guardroom',
            name='detainee_count',
            field=models.PositiveIntegerField(default=0, help_text='Current number of detainees'),
        ),
        migrations.AlterField(
            model_name='guardroom',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Total detainee capacity'),
        ),
        migrations.CreateModel(
            name='DetaineeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accused_no', models.CharField(blank=True, max_length=30)),
                ('accused_rank', models.CharField(blank=True, max_length=60)),
                ('accused_name', models.CharField(blank=True, max_length=120)),
                ('accused_unit', models.CharField(blank=True, max_length=100)),
                ('guard_commander_date', models.DateField(blank=True, null=True)),
                ('guard_commander_time', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('handed_by_name', models.CharField(blank=True, max_length=120)),
                ('handed_by_rank', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('booked_in', 'Booked In'), ('booked_out', 'Booked Out')], default='pending', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('offence_description', models.CharField(blank=True, max_length=200)),
                ('offence_at', models.CharField(blank=True, max_length=150)),
                ('offence_date', models.DateField(blank=True, null=True)),
                ('offence_time', models.CharField(blank=True, max_length=10)),
                ('book_in_signed_name', models.CharField(blank=True, max_length=120)),
                ('book_in_signed_no', models.CharField(blank=True, max_length=30)),
                ('book_in_signed_rank', models.CharField(blank=True, max_length=60)),
                ('book_in_date', models.DateField(blank=True, null=True)),
                ('booked_in_at', models.DateTimeField(blank=True, null=True)),
                ('booked_out_at', models.DateTimeField(blank=True, null=True)),
                ('book_out_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detainee_requests', to='cases.case')),
                ('guardroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detainee_requests', to='guardrooms.guardroom')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardroom_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardroom_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detainee_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
