# Generated by Codex on 2026-07-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardrooms", "0005_guardroomplacementrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="booked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="booked_in_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booked_guardroom_placement_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
