# Generated by Django 6.0.4 on 2026-06-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardrooms', '0005_detainee_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaineerequest',
            name='accused_offence',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
