# Generated by Codex on 2026-07-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.guardrooms.models


class Migration(migrations.Migration):

    dependencies = [
        ("guardrooms", "0006_guardroomplacementrequest_booking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="book_out_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="book_out_rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="book_out_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="book_out_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_out_guardroom_placement_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="book_out_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="book_out_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_book_out_guardroom_placement_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="book_out_status",
            field=models.CharField(
                choices=[
                    ("not_requested", "Not Requested"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="not_requested",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="release_letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.guardrooms.models.release_letter_path,
            ),
        ),
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guardroomplacementrequest",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="released_guardroom_placement_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
