# Generated by Django 6.0.4 on 2026-06-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardrooms', '0006_add_accused_offence'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaineerequest',
            name='book_in_signed_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
