# Generated by Django 6.0.4 on 2026-08-04 19:05

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardrooms', '0007_guardroom_book_out_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardroomplacementrequest',
            name='book_out_comments',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guardroomplacementrequest',
            name='book_out_rejection_reason',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guardroomplacementrequest',
            name='rejection_reason',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guardroomplacementrequest',
            name='reviewer_comments',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
    ]
