# Generated by Django 6.0.4 on 2026-04-24 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_investigation', 'Under Investigation'), ('closed', 'Closed'), ('referred', 'Referred'), ('pending', 'Pending')], default='open', max_length=25)),
                ('offence', models.CharField(blank=True, max_length=200)),
                ('accused_name', models.CharField(blank=True, max_length=120)),
                ('accused_service_number', models.CharField(blank=True, max_length=20)),
                ('accused_rank', models.CharField(blank=True, max_length=60)),
                ('action_taken', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('date_of_offence', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accused_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='formations.unit')),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
