# Generated by Django 6.0.4 on 2026-04-26 11:59

import apps.cases.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
        ('formations', '0005_battalion_formation_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='rfi_document',
            field=models.FileField(blank=True, null=True, upload_to=apps.cases.models.case_attachment_path),
        ),
        migrations.AddField(
            model_name='case',
            name='tasked_battalion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasked_cases', to='formations.battalion'),
        ),
        migrations.AddField(
            model_name='case',
            name='tasking_letter',
            field=models.FileField(blank=True, null=True, upload_to=apps.cases.models.case_attachment_path),
        ),
    ]
