# Generated by Django 6.0.4 on 2026-05-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_rfi_document_case_tasked_battalion_and_more'),
        ('formations', '0007_remove_formation_code'),
        ('offences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='accused_service',
            field=models.CharField(blank=True, choices=[('KA', 'KA'), ('KAF', 'KAF'), ('KN', 'KN')], max_length=5),
        ),
        migrations.AddField(
            model_name='case',
            name='criminal_offence_type',
            field=models.CharField(blank=True, choices=[('dci_civ_police', 'DCI/Civ Police'), ('court_martial', 'Court Martial')], max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='offence_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='offences.offence'),
        ),
        migrations.AddField(
            model_name='case',
            name='offence_type',
            field=models.CharField(blank=True, choices=[('service_offence', 'Service Offence'), ('criminal_offence', 'Criminal Offence')], max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='rfi_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='rfi_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='service_offence_severity',
            field=models.CharField(blank=True, choices=[('serious', 'Serious'), ('minor', 'Minor')], max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='submitting_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cases', to='formations.unit'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('under_investigation', 'Under Investigation'), ('closed', 'Closed'), ('referred', 'Referred'), ('pending', 'Pending')], default='new', max_length=25),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
