# Generated by Django 6.0.4 on 2026-05-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_add_rfi_offence_accused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='tasking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
