# Generated by Django 6.0.4 on 2026-05-05 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_add_tasking_date'),
        ('formations', '0007_remove_formation_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='tasked_detachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasked_cases', to='formations.detachment'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('tasked', 'Tasked'), ('under_investigation', 'Under Investigation'), ('closed', 'Closed'), ('referred', 'Referred'), ('pending', 'Pending')], default='new', max_length=25),
        ),
        migrations.CreateModel(
            name='InvestigationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battalion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_teams', to='formations.battalion')),
                ('members', models.ManyToManyField(blank=True, related_name='investigation_teams', to=settings.AUTH_USER_MODEL)),
                ('team_ic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investigation_teams',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='cases.investigationteam'),
        ),
    ]
