# Generated by Django 6.0.4 on 2026-05-07 21:23

import apps.cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_caseactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='chargesheet',
            field=models.FileField(blank=True, null=True, upload_to=apps.cases.models.case_attachment_path),
        ),
        migrations.AddField(
            model_name='case',
            name='part_one_orders',
            field=models.FileField(blank=True, null=True, upload_to=apps.cases.models.case_attachment_path),
        ),
        migrations.AddField(
            model_name='case',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
