# Generated by Django 6.0.4 on 2026-05-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_investigation_deadline_and_team_detachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='team_assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when an investigation team was last assigned to this case.', null=True),
        ),
        migrations.AlterField(
            model_name='caseactivitylog',
            name='action',
            field=models.CharField(choices=[('case_created', 'Case Created'), ('status_changed', 'Status Changed'), ('attachment_uploaded', 'Attachment Uploaded'), ('attachment_deleted', 'Attachment Deleted'), ('team_assigned', 'Team Assigned'), ('battalion_tasked', 'Battalion Tasked'), ('detachment_tasked', 'Detachment Tasked'), ('case_updated', 'Case Updated')], max_length=30),
        ),
    ]
