# Generated by Django 6.0.4 on 2026-06-29 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_case_close_requested_fields'),
        ('formations', '0008_unit_battalion_relatedname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAccused',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('rank', models.CharField(blank=True, max_length=60)),
                ('service_number', models.CharField(blank=True, max_length=20)),
                ('service', models.CharField(blank=True, choices=[('KA', 'KA'), ('KAF', 'KAF'), ('KN', 'KN')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accused_entries', to='cases.case')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accused_cases', to='formations.unit')),
            ],
            options={
                'db_table': 'case_accused',
                'ordering': ['created_at'],
            },
        ),
    ]
