# Generated by Django 6.0.4 on 2026-05-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_case_close_requested_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='police_station',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
