# Generated by Django 6.0.4 on 2026-07-17 06:35

import apps.cases.models
from django.db import migrations, models


def add_case_location_fields_if_missing(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    table_name = Case._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    for field_name in ("place_of_offence", "police_station"):
        if field_name in existing_columns:
            continue
        field = models.CharField(blank=True, default="", max_length=200)
        field.set_attributes_from_name(field_name)
        schema_editor.add_field(Case, field)


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_exhibitstoragerequest'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_case_location_fields_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='case',
                    name='place_of_offence',
                    field=models.CharField(blank=True, default='', max_length=200),
                ),
                migrations.AddField(
                    model_name='case',
                    name='police_station',
                    field=models.CharField(blank=True, default='', max_length=200),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='caseactivitylog',
            name='action',
            field=models.CharField(choices=[('case_created', 'Case Created'), ('status_changed', 'Status Changed'), ('attachment_uploaded', 'Attachment Uploaded'), ('attachment_deleted', 'Attachment Deleted'), ('team_assigned', 'Team Assigned'), ('battalion_tasked', 'Battalion Tasked'), ('detachment_tasked', 'Detachment Tasked'), ('case_updated', 'Case Updated'), ('brief_attached', 'Brief Attached'), ('brief_updated', 'Brief Updated'), ('brief_forwarded', 'Brief Forwarded')], max_length=30),
        ),
        migrations.AlterField(
            model_name='casebrief',
            name='file',
            field=models.FileField(upload_to=apps.cases.models.case_brief_path),
        ),
    ]
