# Generated by Django 6.0.4 on 2026-08-04 19:05

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0035_alter_caseactivitylog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='action_taken',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='mentioning_remarks',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='remarks',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='caseactivitylog',
            name='detail',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casebackbrief',
            name='note',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casebrief',
            name='approved_note',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casebrief',
            name='forwarded_note',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casebrief',
            name='summary',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casebriefforward',
            name='note',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casecourtmartialhearing',
            name='remarks',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casecourtmartialmilestone',
            name='action_remarks',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casecourtmartialmilestone',
            name='planning_comment',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exhibitstoragerequest',
            name='decline_reason',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exhibitstoragerequest',
            name='description',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exhibitstoragerequest',
            name='lifecycle_decline_reason',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exhibitstoragerequest',
            name='lifecycle_reason',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exhibitstoragerequest',
            name='lifecycle_review_comments',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exhibitstoragerequest',
            name='reviewer_comments',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
    ]
