# Generated by Django 6.0.4 on 2026-08-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0037_repair_part_one_orders_column'),
        ('cases', '0038_case_accused_briefs_exhibit_storage'),
    ]

    operations = [
    ]
