# Generated by Django 6.0.4 on 2026-09-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0041_case_closure_basis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseCourtMartialAttachment',
        ),
    ]
