# Generated by Django 6.0.4 on 2026-09-05 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0043_backfill_incident_case_accused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='place_of_offence',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='police_station',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='casebriefforward',
            name='forwarded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
