# Generated by Django 6.0.4 on 2026-09-09 03:34

import apps.cases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0045_backfill_incident_case_descriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('rfi', 'RFI Case'), ('incident', 'Incident Case'), ('rta', 'Road Traffic Accident')], default='rfi', max_length=25),
        ),
        migrations.AddField(
            model_name='case',
            name='rta_damage_authority',
            field=models.FileField(blank=True, null=True, upload_to=apps.cases.models.case_attachment_path),
        ),
        migrations.AddField(
            model_name='case',
            name='rta_damage_authority_source',
            field=models.CharField(blank=True, choices=[('hq_ka_moves', 'HQ KA Moves'), ('legal', 'Legal')], max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='rta_damage_authority_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='rta_service_vehicle_damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='traffic_accident_report',
            field=models.FileField(blank=True, null=True, upload_to=apps.cases.models.case_attachment_path),
        ),
        migrations.AddField(
            model_name='case',
            name='traffic_accident_report_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='traffic_accident_report_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_traffic_accident_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casebrief',
            name='forwarded_to_role',
            field=models.CharField(blank=True, choices=[('hod', 'HOD'), ('co', 'Commanding Officer'), ('oc', 'OC'), ('corps_cmd', 'Corps Cmd'), ('detachment', 'IC Cases'), ('adj', 'Adjutant'), ('2ic', '2IC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='casebriefforward',
            name='to_role',
            field=models.CharField(choices=[('hod', 'HOD'), ('co', 'Commanding Officer'), ('oc', 'OC'), ('corps_cmd', 'Corps Cmd'), ('detachment', 'IC Cases'), ('adj', 'Adjutant'), ('2ic', '2IC')], max_length=20),
        ),
    ]
