# Generated by Django 6.0.4 on 2026-09-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0051_case_can_be_closed'),
        ('formations', '0010_remove_detachment_battalion_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='tasked_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasked_cases', to='formations.company'),
        ),
    ]
