# Generated by Django 6.0.4 on 2026-09-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0057_case_number_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebrief',
            name='forwarded_to_role',
            field=models.CharField(blank=True, choices=[('ic_cases', 'IC Cases'), ('hod', 'HOD'), ('co', 'Commanding Officer'), ('oc', 'OC'), ('corps_cmd', 'Corps Cmd'), ('detachment', 'Legacy IC Cases'), ('detachment_ic', 'Detachment IC'), ('detachment_commander', 'Detachment Commander'), ('adj', 'Adjutant'), ('2ic', '2IC'), ('company_oc', 'Company OC'), ('company_2ic', 'Company 2IC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='casebriefforward',
            name='to_role',
            field=models.CharField(choices=[('ic_cases', 'IC Cases'), ('hod', 'HOD'), ('co', 'Commanding Officer'), ('oc', 'OC'), ('corps_cmd', 'Corps Cmd'), ('detachment', 'Legacy IC Cases'), ('detachment_ic', 'Detachment IC'), ('detachment_commander', 'Detachment Commander'), ('adj', 'Adjutant'), ('2ic', '2IC'), ('company_oc', 'Company OC'), ('company_2ic', 'Company 2IC')], max_length=20),
        ),
    ]
