# Generated by Django 6.0.4 on 2026-09-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0058_alter_casebrief_forwarded_to_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseactivitylog',
            name='action',
            field=models.CharField(choices=[('case_created', 'Case Created'), ('status_changed', 'Status Changed'), ('attachment_uploaded', 'Attachment Uploaded'), ('attachment_deleted', 'Attachment Deleted'), ('team_assigned', 'Team Assigned'), ('battalion_tasked', 'Battalion Tasked'), ('detachment_tasked', 'Company Tasked'), ('case_updated', 'Case Updated'), ('brief_attached', 'Brief Attached'), ('brief_updated', 'Brief Updated'), ('brief_forwarded', 'Brief Forwarded'), ('case_transferred', 'Case Transferred')], max_length=30),
        ),
    ]
