# Generated by Django 6.0.4 on 2026-09-30 09:11

import apps.common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_hod_brief_roles(apps, schema_editor):
    CaseBrief = apps.get_model("cases", "CaseBrief")
    CaseBriefForward = apps.get_model("cases", "CaseBriefForward")
    CaseBrief.objects.filter(forwarded_to_role="hod").update(forwarded_to_role="hob")
    CaseBrief.objects.filter(forwarded_from_role="hod").update(forwarded_from_role="hob")
    CaseBriefForward.objects.filter(from_role="hod").update(from_role="hob")
    CaseBriefForward.objects.filter(to_role="hod").update(to_role="hob")


def restore_hod_brief_roles(apps, schema_editor):
    CaseBrief = apps.get_model("cases", "CaseBrief")
    CaseBriefForward = apps.get_model("cases", "CaseBriefForward")
    CaseBrief.objects.filter(forwarded_to_role="hob").update(forwarded_to_role="hod")
    CaseBrief.objects.filter(forwarded_from_role="hob").update(forwarded_from_role="hod")
    CaseBriefForward.objects.filter(from_role="hob").update(from_role="hod")
    CaseBriefForward.objects.filter(to_role="hob").update(to_role="hod")


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0059_alter_caseactivitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(rename_hod_brief_roles, restore_hod_brief_roles),
        migrations.AlterField(
            model_name='casebrief',
            name='forwarded_to_role',
            field=models.CharField(blank=True, choices=[('ic_cases', 'IC Cases'), ('hob', 'HOB'), ('co', 'Commanding Officer'), ('oc', 'OC'), ('corps_cmd', 'Corps Cmd'), ('detachment', 'Legacy IC Cases'), ('detachment_ic', 'Detachment IC'), ('detachment_commander', 'Detachment Commander'), ('adj', 'Adjutant'), ('2ic', '2IC'), ('company_oc', 'Company OC'), ('company_2ic', 'Company 2IC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='casebriefforward',
            name='to_role',
            field=models.CharField(choices=[('ic_cases', 'IC Cases'), ('hob', 'HOB'), ('co', 'Commanding Officer'), ('oc', 'OC'), ('corps_cmd', 'Corps Cmd'), ('detachment', 'Legacy IC Cases'), ('detachment_ic', 'Detachment IC'), ('detachment_commander', 'Detachment Commander'), ('adj', 'Adjutant'), ('2ic', '2IC'), ('company_oc', 'Company OC'), ('company_2ic', 'Company 2IC')], max_length=20),
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', apps.common.fields.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_comments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_comments', to='cases.case')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='cases.casecomment')),
            ],
            options={
                'db_table': 'case_comments',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
