# Generated by Django 6.0.4 on 2026-04-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('incident', 'Incident'), ('case', 'Case'), ('morning_brief', 'Morning Brief'), ('system', 'System'), ('alert', 'Alert')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
