# Generated by Django 6.0.4 on 2026-09-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_case_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
