# Generated by Django 6.0.4 on 2026-07-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_adj_2ic_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('co', 'Commanding Officer'), ('corps_cmd', 'Corps Commander'), ('investigator', 'Investigator'), ('duty_officer', 'Duty Officer'), ('hod', 'Head of Department'), ('guardroom_ic', 'Guardroom IC'), ('detachment', 'Detachment IC'), ('personnel', 'Personnel'), ('legal', 'Legal Officer'), ('order_nco', 'Order NCO'), ('mpc_hqs', 'MPC HQS Admin'), ('bsm', 'BSM'), ('cop', 'COP'), ('adj', 'Adjutant'), ('2ic', '2nd in Command')], default='personnel', max_length=20),
        ),
    ]
