# Generated by Django 6.0.4 on 2026-08-04 22:32

import apps.common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passkeycredential_webauthnchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', apps.common.fields.EncryptedTextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_verified_counter', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_totp_devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TOTPLoginChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_totp_login_challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='passkeycredential',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='webauthnchallenge',
            name='user_webaut_user_id_23443b_idx',
        ),
        migrations.RemoveIndex(
            model_name='webauthnchallenge',
            name='user_webaut_consume_ba94a6_idx',
        ),
        migrations.AddField(
            model_name='totpdevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='totploginchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_login_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PasskeyCredential',
        ),
        migrations.RemoveField(
            model_name='webauthnchallenge',
            name='user',
        ),
        migrations.AddIndex(
            model_name='totploginchallenge',
            index=models.Index(fields=['user', 'expires_at'], name='user_totp_l_user_id_63d41e_idx'),
        ),
        migrations.AddIndex(
            model_name='totploginchallenge',
            index=models.Index(fields=['consumed_at'], name='user_totp_l_consume_ddccb3_idx'),
        ),
        migrations.DeleteModel(
            name='WebAuthnChallenge',
        ),
    ]
