# Generated by Django 6.0.4 on 2026-08-04 23:23

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_totpdevice_totploginchallenge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('account', 'Account'), ('ip', 'IP Address'), ('account_ip', 'Account + IP')], max_length=20)),
                ('key_hash', models.CharField(max_length=64)),
                ('label', apps.common.fields.EncryptedTextField(blank=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('first_failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_login_throttles',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['scope', 'locked_until'], name='user_login__scope_66a397_idx'), models.Index(fields=['last_failed_at'], name='user_login__last_fa_00c01e_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key_hash'), name='uniq_login_throttle_scope_key')],
            },
        ),
    ]
