# Generated by Codex on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_legacy_mfa_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginthrottle",
            name="scope",
            field=models.CharField(
                choices=[
                    ("account", "Account"),
                    ("ip", "IP Address"),
                    ("account_ip", "Account + IP"),
                    ("password_reset_email", "Password Reset Email"),
                    ("password_reset_ip", "Password Reset IP"),
                    ("reset_confirm_ip", "Password Reset Confirm IP"),
                    ("reset_confirm_uid", "Password Reset Confirm UID"),
                ],
                max_length=20,
            ),
        ),
    ]
