# Generated by Codex on 2026-08-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_merge_20260816_1324"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_exempt",
            field=models.BooleanField(
                default=False,
                help_text="Exempts the user from Google Authenticator setup and verification.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_otp_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Requires an emailed one-time code after password login for MFA-exempt users.",
            ),
        ),
        migrations.CreateModel(
            name="EmailOTPLoginChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("challenge_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("code_hash", models.CharField(max_length=64)),
                ("sent_to", models.EmailField(max_length=254)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otp_login_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_email_otp_login_challenges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emailotploginchallenge",
            index=models.Index(fields=["user", "expires_at"], name="user_email__user_id_8fb0a5_idx"),
        ),
        migrations.AddIndex(
            model_name="emailotploginchallenge",
            index=models.Index(fields=["consumed_at"], name="user_email__consume_96691d_idx"),
        ),
    ]
