# Generated by Django 6.0.4 on 2026-09-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_email_otp_mfa_exemption'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotploginchallenge',
            new_name='user_email__user_id_3c7a66_idx',
            old_name='user_email__user_id_8fb0a5_idx',
        ),
        migrations.RenameIndex(
            model_name='emailotploginchallenge',
            new_name='user_email__consume_2070f2_idx',
            old_name='user_email__consume_96691d_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('co', 'Commanding Officer'), ('oc', 'Officer Commanding'), ('corps_cmd', 'Corps Commander'), ('investigator', 'Investigator'), ('duty_officer', 'Duty Officer'), ('hod', 'Head of Department'), ('guardroom_ic', 'Guardroom IC'), ('detachment', 'IC COY'), ('personnel', 'Personnel'), ('legal', 'Legal Officer'), ('order_nco', 'Order NCO'), ('mpc_hqs', 'MPC HQS Admin'), ('bsm', 'BSM'), ('cop', 'COP'), ('adj', 'Adjutant'), ('2ic', '2nd in Command'), ('so1_legal', 'SO 1 Legal'), ('so1_ops', 'SO 1 OPs'), ('so2_legal', 'SO 2 Legal'), ('so2_ops', 'SO 2 OPs')], default='personnel', max_length=20),
        ),
    ]
