# Generated by Django 6.0.4 on 2026-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('co', 'Commanding Officer'), ('oc', 'Officer Commanding'), ('corps_cmd', 'Corps Commander'), ('investigator', 'Investigator'), ('duty_officer', 'Duty Officer'), ('hod', 'Head of Department'), ('guardroom_ic', 'Guardroom IC'), ('detachment', 'IC Cases'), ('personnel', 'Personnel'), ('legal', 'Legal Officer'), ('order_nco', 'Order NCO'), ('mpc_hqs', 'MPC HQS Admin'), ('bsm', 'BSM'), ('cop', 'COP'), ('adj', 'Adjutant'), ('2ic', '2nd in Command'), ('docus_clerk', 'Docus Clerk'), ('commandant', 'Commandant'), ('ci', 'Chief Instructor'), ('si', 'SI'), ('so1_legal', 'SO 1 Legal'), ('so1_ops', 'SO 1 OPs'), ('so2_legal', 'SO 2 Legal'), ('so2_ops', 'SO 2 OPs')], default='personnel', max_length=20),
        ),
    ]
