# Generated by Django 6.0.4 on 2026-09-30 09:11

from django.db import migrations, models


def rename_hod_role(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(role="hod").update(role="hob")


def restore_hod_role(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(role="hob").update(role="hod")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_company_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(rename_hod_role, restore_hod_role),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('co', 'Commanding Officer'), ('company_cmd', 'Company Commander'), ('oc', 'Officer Commanding'), ('corps_cmd', 'Corps Commander'), ('sec_corps_cmd', 'Secretary Corps Commander'), ('investigator', 'Investigator'), ('duty_officer', 'Duty Officer'), ('hob', 'HOB'), ('guardroom_ic', 'Guardroom IC'), ('detachment', 'Detachment IC'), ('ic_cases', 'IC Cases'), ('det_cmdr', 'Detachment Commander'), ('pltn_cmdr', 'Platoon Commander'), ('det_2ic', 'Detachment 2IC'), ('personnel', 'Personnel'), ('legal', 'Legal Officer'), ('order_nco', 'Order NCO'), ('mpc_hqs', 'MPC HQS Admin'), ('bsm', 'BSM'), ('cop', 'COP'), ('adj', 'Adjutant'), ('2ic', '2nd in Command'), ('docus_clerk', 'Docus Clerk'), ('commandant', 'Commandant'), ('ci', 'Chief Instructor'), ('si', 'SI'), ('so1_legal', 'SO 1 Legal'), ('so1_ops', 'SO 1 OPs'), ('so2_legal', 'SO 2 Legal'), ('so2_ops', 'SO 2 OPs')], default='personnel', max_length=20),
        ),
    ]
