# Generated by Django 6.0.4 on 2026-08-04 19:05

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='query_string',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
    ]
