# Generated by Django 6.0.4 on 2026-09-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_description_and_more'),
        ('formations', '0011_alter_company_battalion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='detachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='formations.detachment'),
        ),
    ]
