# Generated by Django 6.0.4 on 2026-04-24 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('incident_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date_occurred', models.DateTimeField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=25)),
                ('is_belated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battalion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formations.battalion')),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-date_occurred'],
            },
        ),
    ]
