# Generated by Django 6.0.4 on 2026-07-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_initial'),
        ('morningbriefs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='morning_brief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='morningbriefs.morningbrief'),
        ),
    ]
