# Generated by Django 6.0.4 on 2026-07-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_casebrief_oc_forward_role'),
        ('incidents', '0003_incident_morning_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='converted_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_incident', to='cases.case'),
        ),
    ]
