# Generated by Django 6.0.4 on 2026-08-04 19:05

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incident_report_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='action_taken',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='damages',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=apps.common.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='history',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='how_occurred',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='injuries',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
    ]
