# Generated by Django 6.0.4 on 2026-09-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_alter_incident_action_taken_alter_incident_damages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='rta_casualties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='incident',
            name='rta_vehicles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='incident',
            name='civilian',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='incident',
            name='service_member',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='incident',
            name='service_vehicle',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
