# Generated by Django 6.0.4 on 2026-09-21 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0011_alter_company_battalion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('scope', models.CharField(choices=[('battalion', 'Battalion'), ('corps', 'Corps')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battalion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_events', to='formations.battalion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_todo_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_todo_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'todo_events',
                'ordering': ['event_date', 'event_time', 'title'],
                'indexes': [models.Index(fields=['scope', 'event_date'], name='todo_events_scope_dd1dc5_idx'), models.Index(fields=['battalion', 'event_date'], name='todo_events_battali_cb1de5_idx')],
            },
        ),
    ]
