# Generated by Django 6.0.4 on 2026-04-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MorningBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('late', 'Late'), ('belated', 'Belated')], default='pending', max_length=10)),
                ('total_strength', models.PositiveIntegerField(default=0)),
                ('present', models.PositiveIntegerField(default=0)),
                ('absent', models.PositiveIntegerField(default=0)),
                ('sick', models.PositiveIntegerField(default=0)),
                ('on_leave', models.PositiveIntegerField(default=0)),
                ('on_duty', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'morning_briefs',
                'ordering': ['-date'],
            },
        ),
    ]
