# Generated by Django 6.0.4 on 2026-04-24 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        ('morningbriefs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='morningbrief',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_briefs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='morningbrief',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morning_briefs', to='formations.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='morningbrief',
            unique_together={('date', 'unit')},
        ),
    ]
