# Generated by Django 6.0.4 on 2026-07-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0008_unit_battalion_relatedname'),
        ('morningbriefs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morningbrief',
            name='battalion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morning_briefs', to='formations.battalion'),
        ),
        migrations.AddField(
            model_name='morningbrief',
            name='detachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morning_briefs', to='formations.detachment'),
        ),
        migrations.AlterField(
            model_name='morningbrief',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morning_briefs', to='formations.unit'),
        ),
    ]
