# Generated by Django 6.0.4 on 2026-07-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morningbriefs', '0006_populate_morningbrief_serials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morningbrief',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Auto Publish'), ('published', 'Published'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('late', 'Late'), ('belated', 'Belated')], default='draft', max_length=10),
        ),
    ]
