# Generated by Django 6.0.4 on 2026-08-04 19:05

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morningbriefs', '0007_alter_morningbrief_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morningbrief',
            name='remarks',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
    ]
