# Generated by Django 6.0.4 on 2026-05-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_battalion_formation_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='unit',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='unit',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='formations.formation'),
        ),
        migrations.AddField(
            model_name='unit',
            name='location_county',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='unit',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='unit',
            name='service',
            field=models.CharField(choices=[('KA', 'Kenya Army'), ('KAF', 'Kenya Air Force'), ('KN', 'Kenya Navy')], default='KA', max_length=3),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='company',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='unit',
            name='battalion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='formations.battalion'),
        ),
    ]
