# Generated by Django 6.0.4 on 2026-05-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0006_formation_location_unit_email_unit_formation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='code',
        ),
    ]
