# Generated by Django 6.0.4 on 2026-05-08 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0007_remove_formation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='battalion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battalion_units', to='formations.battalion'),
        ),
    ]
