# Generated by Django 6.0.4 on 2026-09-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0009_alter_detachment_aor_optional'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="detachment",
            new_name="company",
        ),
        migrations.AlterModelTable(
            name="company",
            table="companies",
        ),
        migrations.CreateModel(
            name="Detachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("aor", models.CharField(blank=True, max_length=200)),
                ("mobile_no", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detachments",
                        to="formations.company",
                    ),
                ),
            ],
            options={"db_table": "detachments", "ordering": ["name"]},
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO detachments (id, company_id, name, aor, mobile_no, email, created_at)
                SELECT id, id, 'Main Detachment', aor, mobile_no, email, created_at
                FROM companies;
                SELECT setval(
                    pg_get_serial_sequence('detachments', 'id'),
                    COALESCE((SELECT MAX(id) FROM detachments), 1),
                    true
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
