# Generated by Django 6.0.4 on 2026-09-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0010_remove_detachment_battalion_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='battalion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='formations.battalion'),
        ),
    ]
