# Generated by Django 6.0.4 on 2026-07-19 18:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0008_unit_battalion_relatedname'),
        ('incidents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('returned', 'Returned for Correction'), ('declined', 'Declined'), ('approved', 'Approved'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=25)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.TextField(blank=True)),
                ('returned_reason', models.TextField(blank=True)),
                ('declined_reason', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_duty_rosters', to=settings.AUTH_USER_MODEL)),
                ('battalion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_rosters', to='formations.battalion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duty_rosters', to=settings.AUTH_USER_MODEL)),
                ('detachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_rosters', to='formations.detachment')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_rosters_for_approval', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_duty_rosters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'duty_rosters',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyRosterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'duty_roster_assignments',
                'ordering': ['roster_post__starts_at', 'personnel__name'],
            },
        ),
        migrations.CreateModel(
            name='DutyRosterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=120)),
                ('duty_type', models.CharField(choices=[('12h', '12 Hours'), ('24h', '24 Hours'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='24h', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('required_personnel', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('assigned_personnel', models.ManyToManyField(blank=True, related_name='duty_roster_posts', through='dutyrooms.DutyRosterAssignment', to=settings.AUTH_USER_MODEL)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dutyrooms.dutyroster')),
            ],
            options={
                'db_table': 'duty_roster_posts',
                'ordering': ['starts_at', 'post_name'],
            },
        ),
        migrations.AddField(
            model_name='dutyrosterassignment',
            name='roster_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dutyrooms.dutyrosterpost'),
        ),
        migrations.CreateModel(
            name='OccurrenceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battalion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_books', to='formations.battalion')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_occurrence_books', to=settings.AUTH_USER_MODEL)),
                ('detachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_books', to='formations.detachment')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_occurrence_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'occurrence_books',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dutyrosterassignment',
            unique_together={('roster_post', 'personnel')},
        ),
        migrations.CreateModel(
            name='OccurrenceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_type', models.CharField(choices=[('routine', 'Routine'), ('incident', 'Incident'), ('message', 'Message'), ('order', 'Order'), ('movement', 'Movement'), ('visitor', 'Visitor'), ('guardroom', 'Guardroom'), ('other', 'Other')], default='routine', max_length=25)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('requires_investigation', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('converted_to_incident', 'Converted to Incident')], default='recorded', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dutyrooms.occurrencebook')),
                ('linked_incident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_ob_entry', to='incidents.incident')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_occurrence_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'occurrence_entries',
                'ordering': ['-occurred_at', '-serial_no'],
                'unique_together': {('book', 'serial_no')},
            },
        ),
    ]
