# Generated by Django 6.0.4 on 2026-08-04 19:05

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dutyrooms', '0007_occurrenceentry_rta_json_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyroster',
            name='approval_note',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dutyroster',
            name='declined_reason',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dutyroster',
            name='returned_reason',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dutyrosterpost',
            name='notes',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occurrenceentry',
            name='action_taken',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occurrenceentry',
            name='damages',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occurrenceentry',
            name='description',
            field=apps.common.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='occurrenceentry',
            name='history',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occurrenceentry',
            name='how_occurred',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='occurrenceentry',
            name='injuries',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
    ]
