# Generated by Django 6.0.4 on 2026-09-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutyrooms', '0008_alter_dutyroster_approval_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceentry',
            name='civilian',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='occurrenceentry',
            name='service_member',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='occurrenceentry',
            name='service_vehicle',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
